In [88]:
import datetime as dt
import matplotlib.pyplot as plt
from matplotlib import style
import datetime
import numpy as np
import yfinance as yf
import pandas as pd

In [102]:
start="2021-01-01" #YYYY/MM/DD
end="2021-11-05"

In [115]:
fin = pd.DataFrame(columns =['Ticker', 'Last_Dt','Date_30','Date_90','Date_180','Returns_30_Days','Returns_90_Days','Returns_180_Days'])

In [104]:
ticker = ['AUBANK.NS', 'AARTIIND.NS', 'ADANIENT.NS']

In [114]:
##data pull for tickers from yahoo finance##
ticker = ['AUBANK.NS', 'AARTIIND.NS', 'ADANIENT.NS', 'ATGL.NS', 'ABCAPITAL.NS', 'ABFRL.NS', 'AJANTPHARM.NS', 'APLLTD.NS', 'AMARAJABAT.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'ASHOKLEY.NS', 'BALKRISIND.NS', 'BANKINDIA.NS', 'BATAINDIA.NS', 'BEL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BBTC.NS', 'CESC.NS', 'CANBK.NS', 'CASTROLIND.NS', 'CHOLAFIN.NS', 'CUB.NS', 'COFORGE.NS', 'COROMANDEL.NS', 'CROMPTON.NS', 'CUMMINSIND.NS', 'DALBHARAT.NS', 'DHANI.NS', 'LALPATHLAB.NS', 'EDELWEISS.NS', 'EMAMILTD.NS', 'ENDURANCE.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'FRETAIL.NS', 'GMRINFRA.NS', 'GLENMARK.NS', 'GODREJAGRO.NS', 'GODREJIND.NS', 'GODREJPROP.NS', 'GUJGASLTD.NS', 'GSPL.NS', 'HUDCO.NS', 'ISEC.NS', 'IDFCFIRSTB.NS', 'IBULHSGFIN.NS', 'INDHOTEL.NS', 'IRCTC.NS', 'IPCALAB.NS', 'JSWENERGY.NS', 'JINDALSTEL.NS', 'JUBLFOOD.NS', 'L&TFH.NS', 'LTTS.NS', 'LICHSGFIN.NS', 'MRF.NS', 'MGL.NS', 'M&MFIN.NS', 'MANAPPURAM.NS', 'MFSL.NS', 'MINDTREE.NS', 'MPHASIS.NS', 'NATCOPHARM.NS', 'NATIONALUM.NS', 'NAVINFLUOR.NS', 'NAM-INDIA.NS', 'OBEROIRLTY.NS', 'OIL.NS', 'PIIND.NS', 'PAGEIND.NS', 'PFIZER.NS', 'POLYCAB.NS', 'PRESTIGE.NS', 'RBLBANK.NS', 'RECLTD.NS', 'RAJESHEXPO.NS', 'SRF.NS', 'SANOFI.NS', 'SRTRANSFIN.NS', 'SAIL.NS', 'SUNTV.NS', 'SYNGENE.NS', 'TVSMOTOR.NS', 'TATACHEM.NS', 'TATAPOWER.NS', 'RAMCOCEM.NS', 'TORNTPOWER.NS', 'TRENT.NS', 'UNIONBANK.NS', 'VGUARD.NS', 'VBL.NS', 'IDEA.NS', 'VOLTAS.NS', 'WHIRLPOOL.NS', 'YESBANK.NS', 'ZEEL.NS']

In [116]:
for x in ticker :
    
    df = yf.download(x,start,end)
    df['Date'] = df.index
    print(x)
    table = pd.DataFrame([[x,
                           df.tail(1).Date[0],
                           df.tail(30).Date[0],
                           df.tail(90).Date[0],
                           df.tail(180).Date[0],
                           (df.tail(1).values[:1,3][0] - df.tail(30).head(1).values[:1,3][0])/df.tail(30).head(1).values[:1,3][0],
                           (df.tail(1).values[:1,3][0] - df.tail(90).head(1).values[:1,3][0])/df.tail(90).head(1).values[:1,3][0],
                           (df.tail(1).values[:1,3][0] - df.tail(180).head(1).values[:1,3][0])/df.tail(180).head(1).values[:1,3][0]
                          ]],
                     columns =['Ticker','Last_Dt','Date_30','Date_90','Date_180','Returns_30_Days','Returns_90_Days','Returns_180_Days'])
    fin = fin.append(table)

[*********************100%***********************]  1 of 1 completed
AUBANK.NS
[*********************100%***********************]  1 of 1 completed
AARTIIND.NS
[*********************100%***********************]  1 of 1 completed
ADANIENT.NS
[*********************100%***********************]  1 of 1 completed
ATGL.NS
[*********************100%***********************]  1 of 1 completed
ABCAPITAL.NS
[*********************100%***********************]  1 of 1 completed
ABFRL.NS
[*********************100%***********************]  1 of 1 completed
AJANTPHARM.NS
[*********************100%***********************]  1 of 1 completed
APLLTD.NS
[*********************100%***********************]  1 of 1 completed
AMARAJABAT.NS
[*********************100%***********************]  1 of 1 completed
APOLLOHOSP.NS
[*********************100%***********************]  1 of 1 completed
APOLLOTYRE.NS
[*********************100%***********************]  1 of 1 completed
ASHOKLEY.NS
[*********************100%***********************]  1 of 1 completed
BALKRISIND.NS
[*********************100%***********************]  1 of 1 completed
BANKINDIA.NS
[*********************100%***********************]  1 of 1 completed
BATAINDIA.NS
[*********************100%***********************]  1 of 1 completed
BEL.NS
[*********************100%***********************]  1 of 1 completed
BHARATFORG.NS
[*********************100%***********************]  1 of 1 completed
BHEL.NS
[*********************100%***********************]  1 of 1 completed
BBTC.NS
[*********************100%***********************]  1 of 1 completed
CESC.NS
[*********************100%***********************]  1 of 1 completed
CANBK.NS
[*********************100%***********************]  1 of 1 completed
CASTROLIND.NS
[*********************100%***********************]  1 of 1 completed
CHOLAFIN.NS
[*********************100%***********************]  1 of 1 completed
CUB.NS
[*********************100%***********************]  1 of 1 completed
COFORGE.NS
[*********************100%***********************]  1 of 1 completed
COROMANDEL.NS
[*********************100%***********************]  1 of 1 completed
CROMPTON.NS
[*********************100%***********************]  1 of 1 completed
CUMMINSIND.NS
[*********************100%***********************]  1 of 1 completed
DALBHARAT.NS
[*********************100%***********************]  1 of 1 completed
DHANI.NS
[*********************100%***********************]  1 of 1 completed
LALPATHLAB.NS
[*********************100%***********************]  1 of 1 completed
EDELWEISS.NS
[*********************100%***********************]  1 of 1 completed
EMAMILTD.NS
[*********************100%***********************]  1 of 1 completed
ENDURANCE.NS
[*********************100%***********************]  1 of 1 completed
ESCORTS.NS
[*********************100%***********************]  1 of 1 completed
EXIDEIND.NS
[*********************100%***********************]  1 of 1 completed
FEDERALBNK.NS
[*********************100%***********************]  1 of 1 completed
FORTIS.NS
[*********************100%***********************]  1 of 1 completed
FRETAIL.NS
[*********************100%***********************]  1 of 1 completed
GMRINFRA.NS
[*********************100%***********************]  1 of 1 completed
GLENMARK.NS
[*********************100%***********************]  1 of 1 completed
GODREJAGRO.NS
[*********************100%***********************]  1 of 1 completed
GODREJIND.NS
[*********************100%***********************]  1 of 1 completed
GODREJPROP.NS
[*********************100%***********************]  1 of 1 completed
GUJGASLTD.NS
[*********************100%***********************]  1 of 1 completed
GSPL.NS
[*********************100%***********************]  1 of 1 completed
HUDCO.NS
[*********************100%***********************]  1 of 1 completed
ISEC.NS
[*********************100%***********************]  1 of 1 completed
IDFCFIRSTB.NS
[*********************100%***********************]  1 of 1 completed
IBULHSGFIN.NS
[*********************100%***********************]  1 of 1 completed
INDHOTEL.NS
[*********************100%***********************]  1 of 1 completed
IRCTC.NS
[*********************100%***********************]  1 of 1 completed
IPCALAB.NS
[*********************100%***********************]  1 of 1 completed
JSWENERGY.NS
[*********************100%***********************]  1 of 1 completed
JINDALSTEL.NS
[*********************100%***********************]  1 of 1 completed
JUBLFOOD.NS
[*********************100%***********************]  1 of 1 completed
L&TFH.NS
[*********************100%***********************]  1 of 1 completed
LTTS.NS
[*********************100%***********************]  1 of 1 completed
LICHSGFIN.NS
[*********************100%***********************]  1 of 1 completed
MRF.NS
[*********************100%***********************]  1 of 1 completed
MGL.NS
[*********************100%***********************]  1 of 1 completed
M&MFIN.NS
[*********************100%***********************]  1 of 1 completed
MANAPPURAM.NS
[*********************100%***********************]  1 of 1 completed
MFSL.NS
[*********************100%***********************]  1 of 1 completed
MINDTREE.NS
[*********************100%***********************]  1 of 1 completed
MPHASIS.NS
[*********************100%***********************]  1 of 1 completed
NATCOPHARM.NS
[*********************100%***********************]  1 of 1 completed
NATIONALUM.NS
[*********************100%***********************]  1 of 1 completed
NAVINFLUOR.NS
[*********************100%***********************]  1 of 1 completed
NAM-INDIA.NS
[*********************100%***********************]  1 of 1 completed
OBEROIRLTY.NS
[*********************100%***********************]  1 of 1 completed
OIL.NS
[*********************100%***********************]  1 of 1 completed
PIIND.NS
[*********************100%***********************]  1 of 1 completed
PAGEIND.NS
[*********************100%***********************]  1 of 1 completed
PFIZER.NS
[*********************100%***********************]  1 of 1 completed
POLYCAB.NS
[*********************100%***********************]  1 of 1 completed
PRESTIGE.NS
[*********************100%***********************]  1 of 1 completed
RBLBANK.NS
[*********************100%***********************]  1 of 1 completed
RECLTD.NS
[*********************100%***********************]  1 of 1 completed
RAJESHEXPO.NS
[*********************100%***********************]  1 of 1 completed
SRF.NS
[*********************100%***********************]  1 of 1 completed
SANOFI.NS
[*********************100%***********************]  1 of 1 completed
SRTRANSFIN.NS
[*********************100%***********************]  1 of 1 completed
SAIL.NS
[*********************100%***********************]  1 of 1 completed
SUNTV.NS
[*********************100%***********************]  1 of 1 completed
SYNGENE.NS
[*********************100%***********************]  1 of 1 completed
TVSMOTOR.NS
[*********************100%***********************]  1 of 1 completed
TATACHEM.NS
[*********************100%***********************]  1 of 1 completed
TATAPOWER.NS
[*********************100%***********************]  1 of 1 completed
RAMCOCEM.NS
[*********************100%***********************]  1 of 1 completed
TORNTPOWER.NS
[*********************100%***********************]  1 of 1 completed
TRENT.NS
[*********************100%***********************]  1 of 1 completed
UNIONBANK.NS
[*********************100%***********************]  1 of 1 completed
VGUARD.NS
[*********************100%***********************]  1 of 1 completed
VBL.NS
[*********************100%***********************]  1 of 1 completed
IDEA.NS
[*********************100%***********************]  1 of 1 completed
VOLTAS.NS
[*********************100%***********************]  1 of 1 completed
WHIRLPOOL.NS
[*********************100%***********************]  1 of 1 completed
YESBANK.NS
[*********************100%***********************]  1 of 1 completed
ZEEL.NS

In [117]:
fin

,Ticker,Last_Dt,Date_30,Date_90,Date_180,Returns_30_Days,Returns_90_Days,Returns_180_Days
0,AUBANK.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.108785,0.164834,0.113072
0,AARTIIND.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.044115,0.104320,0.578965
0,ADANIENT.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.010242,-0.023792,1.071702
0,ATGL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.022424,0.269038,2.748399
0,ABCAPITAL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.068081,-0.110173,0.188275
...,...,...,...,...,...,...,...,...
0,IDEA.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.052133,-0.043062,-0.200000
0,VOLTAS.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.022866,0.170256,0.130513
0,WHIRLPOOL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.063140,-0.042847,-0.147866
0,YESBANK.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.011538,-0.036630,-0.198171
0,ZEEL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.025299,0.415241,0.459529

In [124]:
nifty = yf.download('^NSEI',start,end)

[*********************100%***********************]  1 of 1 completed

In [125]:
nifty.tail(5)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-10-29,8468.950195,8625.200195,8323.700195,8513.500000,8513.500000,0
2021-11-01,8579.200195,8692.099609,8531.349609,8680.250000,8680.250000,0
2021-11-02,8717.849609,8784.549805,8712.700195,8763.599609,8763.599609,0
2021-11-03,8800.650391,8832.599609,8682.650391,8726.150391,8726.150391,0
2021-11-04,8790.849609,8814.849609,8778.049805,8789.250000,8789.250000,87700

In [126]:
##30 working days nifty returns
nifty_ret_30 = (nifty.tail(1).values[:1,3][0] - nifty.tail(30).head(1).values[:1,3][0])/nifty.tail(30).head(1).values[:1,3][0]
nifty_ret_90 = (nifty.tail(1).values[:1,3][0] - nifty.tail(90).head(1).values[:1,3][0])/nifty.tail(90).head(1).values[:1,3][0]
nifty_ret_180 = (nifty.tail(1).values[:1,3][0] - nifty.tail(180).head(1).values[:1,3][0])/nifty.tail(180).head(1).values[:1,3][0]

In [127]:
fin['alpha_30'] = fin.Returns_30_Days/nifty_ret_30
fin['alpha_90'] = fin.Returns_90_Days/nifty_ret_90
fin['alpha_180'] = fin.Returns_180_Days/nifty_ret_180

In [128]:
fin

,Ticker,Last_Dt,Date_30,Date_90,Date_180,Returns_30_Days,Returns_90_Days,Returns_180_Days,alpha_30,alpha_90,alpha_180
0,AUBANK.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.108785,0.164834,0.113072,1.738474,0.976827,0.371681
0,AARTIIND.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.044115,0.104320,0.578965,0.704996,0.618215,1.903130
0,ADANIENT.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.010242,-0.023792,1.071702,0.163672,-0.140992,3.522818
0,ATGL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.022424,0.269038,2.748399,0.358357,1.594355,9.034332
0,ABCAPITAL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.068081,-0.110173,0.188275,-1.087993,-0.652899,0.618884
...,...,...,...,...,...,...,...,...,...,...,...
0,IDEA.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.052133,-0.043062,-0.200000,-0.833122,-0.255192,-0.657425
0,VOLTAS.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.022866,0.170256,0.130513,-0.365410,1.008956,0.429014
0,WHIRLPOOL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.063140,-0.042847,-0.147866,-1.009022,-0.253914,-0.486054
0,YESBANK.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,0.011538,-0.036630,-0.198171,0.184393,-0.217074,-0.651412
0,ZEEL.NS,2021-11-04,2021-09-23,2021-06-28,2021-02-12,-0.025299,0.415241,0.459529,-0.404292,2.460768,1.510531

In [122]:
fin.to_csv('alpha_v2.csv')

In [130]:
nifty_ret_30

0.06257513131377529

In [87]:
df.tail(30).Date[1]

Timestamp('2021-08-20 00:00:00')

In [111]:
df.tail(1).Date[0]

Timestamp('2021-11-04 00:00:00')

In [129]:
nifty_ret_30

0.06257513131377529